### PR TITLE
Completed config parsing refactor.

### LINKED ISSUE #133: Complete config refactor
The initial configuration refactor did not address validation_utils.py and a few places in k8_utils.py & ansible_configuration.py

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Fixes #133 
Completes moving configuration parsing to config_utils.py and refactors validation_utils.py to use it as well. Additionally, validation_utils.py is now raising Exceptions rather than having to check a return value for each check which causes a ton of extra unnecessary lines of code to manage
#### Do you have any concerns with this PR?
No
#### How can the reviewer verify this PR?
Run CI
#### Any background context you want to provide?
This PR is an extension of 'refactor_and_cleanup' branch that was merged last week
#### Questions:
- Have you connected this PR to the issue it resolves?
yes
- Does the documentation need an update?
no
- Does this add new Python dependencies?
no
- Have you added unit or functional tests for this PR?
yes, unit test coverage up to 89%
- Does this patch update any configuration files?
Does not affect the expected structure. The test config file was fixed and had items added to increase test coverage

### CODE REVIEW

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by spisarski** [comment]
@Sanjhana-Jayagopal - can you inspect the attached e2e logs. There is one failure but it has to do with latency and am hoping this may be due to a slow VM...
[e2e.log.gz](https://github.com/cablelabs/snaps-kubernetes/files/2578226/e2e.log.gz)

**Comment by spisarski** [comment]
CNCF tests all passed. Please review.

**Pull request merged**
