### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skulasekar**
#### Questions:
- Have you connected this PR to the issue it resolves?
- Does the documentation need an update?
- Does this add new Python dependencies?
- Have you added unit or functional tests for this PR?
- Does this patch update any configuration files?

### CODE REVIEW

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by RandyLevensalor** [comment]
Run Tests

**Comment by spisarski** [comment]
@skulasekar - Can I kill this PR?

**Comment by spisarski** [comment]
This PR does not appear to be necessary. Closing

**Pull request closed without merging**
