### PR TITLE
fix for issue#83 Move to overlay2 docker storage driver

### PR DESCRIPTION
**Pull request by chiraggupta06**
#### What does this PR do?
Fix for the issue #83 
#### Do you have any concerns with this PR?
No
#### How can the reviewer verify this PR?
By executing the Kubernetes deployment with this pull request. A user can check docker info for the changes.
#### Any background context you want to provide?
No
#### Screenshots or logs (if appropriate)
No
#### Questions:
- Have you connected this PR to the issue it resolves?
yes
- Does the documentation need an update?
No
- Does this add new Python dependencies?
No
- Have you added unit or functional tests for this PR?
No
- Does this patch update any configuration files?

### CODE REVIEW

**Comment by RandyLevensalor** [comment]
fixes #83

**Comment by spisarski** [comment]
@RandyLevensalor & @Sanjhana-Jayagopal, can you both take a peek and let me know if y'all are fine with merging?

**Comment by Sanjhana-Jayagopal** [comment]
Ran CI and it passed the tests.

**Comment by RandyLevensalor** [comment]
Run Tests

**Pull request merged**
