### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Removes code that is not being used and a few changes to calling ansible playbooks
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
run CI
#### Any background context you want to provide?
Cleanup which will make the migration efforts for using the Ansible API rather than command line easier as well as cleanup of file-based configuration resources.
#### Questions:
- Have you connected this PR to the issue it resolves?
yes
- Does the documentation need an update?
no
- Does this add new Python dependencies?
no
- Have you added unit or functional tests for this PR?
no
- Does this patch update any configuration files?
no

### CODE REVIEW

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by skulasekar** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
Run Tests

**Comment by spisarski** [comment]
CI is running for too long and the SSH connection was lost during the last run so it was unable to obtain the status of the iaas_launch.py and the failure logged was not due to the installation failing as I was monitoring that in realtime. I will be merging this patch so I can continue the refactoring work which will include performance enhancements and should mitigate the possibility of these types of failures in the future.

**Pull request merged**
